# file: _config.yml
url: https://robertthalheim.com/
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
name: RT | The Motion
title: null
bg: grey
### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  grey:      '#202124'
