# file: _config.yml
url: https://robertthalheim.com/
name: The Motion
title: null
bg: grey
### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  grey:      '#202124'
